---
  - name: Clone php-diff
    git:
      repo: https://github.com/tty8747/calc_diff.git
      dest: "{{ locallocationPhpFpmApp }}"
      clone: yes

  - name: —Åreate directory {{ locallocationPhpFpmApp }}
    file:
      path={{ locallocationPhpFpmApp }}
      mode=0755
      owner=root
      group=root
      state=directory
