---
- hosts: web
  remote_user: goto
  become: yes
  become_user: root
  become_method: sudo

  vars:
    site: tty8747.devops.srwx.net
    when: ansible_nodename == "tty8747.devops.srwx.net"
    phpFpmVersion: 7.0
    phpFpmListen: "/run/php/php7.0-fpm.sock"

    locationPhpFpmApp: "/api/diff/"
    locallocationPhpFpmApp: "/srv/phpapp/diff.php"

    locationHtmlApp: "/"
    localLocationHtmlApp: "/srv/www"
   
    locationGoApi: "/api/sum/"
   
#   site: goapp.aaaj.ru
#   when: ansible_nodename == "goapp.aaaj.ru"
#   site: go.aaaj.ru
#   when: ansible_nodename == "go.aaaj.ru"

  roles:
    - aptUpdate
    - nginx 
    - letsencrypt
    - geerlingguy.git
    - php-fpm
    - calcFrontHtml
#   - calcSumGo
#   - calcDiffPhp
